trigger:
- main

pool:
  name: Default 

variables:
- group: Books

steps:
- checkout: self

- script: |
    echo "user.name=$(userName)" > credentials.properties
    echo "user.password=$(userPassword)" >> credentials.properties
    echo "user.first.name=$(userFirstName)" >> credentials.properties
    echo "user.last.name=$(userLastName)" >> credentials.properties
    echo "user.id=$(userId)" >> credentials.properties
  displayName: 'Write credentials to properties file'

- task: Gradle@4
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'Build with Gradle using Java 17'
