trigger:
  branches:
    include:
      - main

pool:
  vmImage: Default

steps:
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx1024m'
      tasks: 'clean test'
      options: '--info'
      publishJUnitResults: true
      testResultsFiles: '**/build/test-results/test/*.xml'
