trigger:
- main

pool:
  name: Default

variables:
- group: Books

steps:
- checkout: self

- script: |
    echo "Variable from group Books:"
    echo "user.name = ${{ variables.userName }}"
  displayName: 'Test variable access from group'
