trigger:
- none

pool:
  name: Default

variables:
- group: Books
- name: System.Debug
  value: true

steps:
- checkout: self

- script: |
    echo "======================"
    echo "🔍 DEBUG: Variable Group Test"
    echo "userName: $(userName)"
    echo "userPassword: $(userPassword)"
    echo "userFirstName: $(userFirstName)"
    echo "userLastName: $(userLastName)"
    echo "userId: $(userId)"
    echo "======================"
  displayName: 'Проверка переменных из Variable Group'

